# color constants
SYS_TRANSPARENT = "systemTransparent"
TOOLBAR_FG_COLOR = "transparent"
TOOLBAR_HOVER_COLOR = "gray75"
TOOLBAR_ICON_COLOR = (104, 104, 104)
TOOLBAR_HEADER_COLOR = "#343434"
TOOLBAR_BUTTON_HEIGHT = 40
TOOLBAR_BUTTON_WIDTH = 40


TOOLBAR_WINDOW_BUTTON_SIZE = 14
TOOLBAR_WINDOW_BUTTON_RADIUS = TOOLBAR_WINDOW_BUTTON_SIZE / 2
TOOLBAR_WINDOW_BUTTON_CLOSE_COLOR = "#FD4646"
ARROW = "arrow"
